language: node_js
branches:
  only:
    - travis
addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts: 104.248.216.164
deploy:
  - sshpass -p $DOPASS ssh team@104.248.216.164
  - ./autodeploy.sh
