language: node_js
branches:
  only:
    - travis
addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts: 104.248.216.164
deploy:
  skip_cleanup: true
  script:
    - sshpass -p $DOPASS ssh team@104.248.216.164
    - ./autodeploy.sh
