#!/bin/bash -e
USER="$(whoami)"
#[ -e "/srv/apps/$USER/$USER.sock" ] && rm "/srv/apps/$USER/dev.sock"
umask 0

. ~/.nvm/nvm.sh
cd ~/dev_portal
NODE_ENV=production PORT="/srv/apps/$USER/dev.sock" \
DB_USER=hackthebay \
DB_PASSWD=ZF9B3uiGFY4wBqSGNlchEpm6 \
DB_NAME=hackthebay \
DB_HOST=mysql \
SENDGRID_APIKEY=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 \
SECRET=AreSecretsReallyMeantToBeKeptHidden?IThinkNot.-gleeb \
RESUMEDIR="/home/h/ha/hackthebay/" \
MAIL_PASSWORD=ddoski2018 \
exec nodemon ~/dev_portal/dist/server.js
