name: Autodeploy

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          --user: "team"
          --host: "104.248.216.164"
          --script: "mkdir test"
