name: Autodeploy

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: github-actions
      - uses: actions/setup-node@master
        with:
          node-version: 8.10.0
      - name: Install dependencies
        run: npm install
      - name: Test build
        run: npm run build
      - name: Slack Notification - Build Failed
        uses: homoluctus/slatify@master
        if: failure()
        with:
          type: failure
          job_name: 'Build'
          channel: '#production'
          url: ${{ secrets.SLACK_WEBHOOK }}
  deploy:
    runs-on: ubuntu-latest
    needs: build # build must succeed before deployment
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          args: --script "'./autodeploy.sh'"
      - name: Slack Notification - Deployment Failed
        uses: homoluctus/slatify@master
        if: failure()
        with:
          type: fail
          job_name: 'Autodeploy'
          channel: '#production'
          url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notification - Build & Deployment Succeeded
        uses: homoluctus/slatify@master
        if: success()
        with:
          type: success
          job_name: 'Autodeploy'
          channel: '#production'
          url: ${{ secrets.SLACK_WEBHOOK }}
