name: Autotest

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 8.10.0
      - name: Install dependencies
        run: npm install
      - name: Test build
        run: npm run build
